print("Important:first you need to collect part3 based subject")
a= float(input("sem1-digitalcomputer&fundamentals:"))
b= float(input("sem1-allied statistical methods:"))
c= float(input("sem1-Practical microporcessor:"))
d= float(input("sem2-programming in c:"))
e= float(input("sem2-applied statistics:"))
f= float(input("sem2-Practical progamming in c:"))
g= float(input("sem2-practical allied statistics:"))
h= float(input("sem3-c++ programming:"))
i= float(input("sem3-data structure algorithm:"))
j= float(input("sem3-allied principles of accountancy:"))
k= float(input("sem3-practical data structure in c++:"))
l= float(input("sem4-programming in java:"))
m= float(input("sem4-allied cost and management accounts:"))
n= float(input("sem4-Practical in java:"))
o= float(input("sem4-practical allied commerce:"))
p= float(input("sem5-visual basic programming:"))
q= float(input("sem5-operating system:"))
r= float(input("sem5-software engineering:"))
s= float(input("sem5-client\server:"))
t= float(input("sem5-Practical VB:"))
u= float(input("sem6-RDBMS:"))
v= float(input("sem6-web designing:"))
w= float(input("sem6-E-commerce:"))
x= float(input("sem6-data mining:"))
y= float(input("sem6- Practical web designing:"))

total= (4*a)+(4*b)+(4*c)+(4*d)+(3*e)+(4*f)+(3*g)+(4*h)+(4*i)+(4*j)+(4*k)+(4*l)+(4*m)+(4*n)+(2*o)+(4*p)+(4*q)+(4*r)+(5*s)+(4*t)+(4*u)+(4*v)+(5*w)+(5*x)+(4*y)
cgpa= total/99
print("core computer science CGPA:",cgpa)